### ISSUE TITLE
Require image for ARM64 architecture

### ISSUE THREAD

**Issue by odidev** [cilium/starwars-docker#2]
@tgraf,  

I am trying to use “cilium/starwars” image over ARM64v8 but it seems it does not have an arm64 supported tag in docker hub. 
I have successfully built the image using command **docker build -t <image_name> .** on arm64 platform. 

May I know how the amd64 image is getting published on Dockerhub?

It would be helpful if you could release arm64 image.

**Comment by odidev** [comment]
@JrCs, any update on the above issue?

**Comment by hhstu** [comment]
@odidev  Another way to make the arm host support amd64,   run  `docker run --privileged --rm tonistiigi/binfmt --install all`          more info:  https://github.com/docker/buildx/#building-multi-platform-images


```bash

root@lc1:~# kubectl  get  pod  -owide
NAME                         READY   STATUS    RESTARTS   AGE     IP           NODE   NOMINATED NODE   READINESS GATES
deathstar-79ccf648bb-fwkdc   1/1     Running   0          2m51s   10.0.1.78    lc3    <none>           <none>
deathstar-79ccf648bb-rtlt8   1/1     Running   0          2m51s   10.0.2.226   lc2    <none>           <none>
root@lc1:~#
root@lc1:~#
root@lc1:~#
root@lc1:~# uname  -a
Linux lc1 5.15.0-47-generic #51-Ubuntu SMP Fri Aug 12 08:18:32 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
root@lc1:~#
```

**Comment by christianhuening** [comment]
would also love to see this :) I can buildx them myself, but maybe it would be nice to add to the out-of-the box experience also on people's home-lab clusters ;-) 
Any hints as to how these images are build?

**Comment by lizrice** [comment]
The [cilium/starwars image](https://hub.docker.com/r/cilium/starwars/tags) now includes ARM and x86 versions
